WIP: Bottom navigation bindings
InsidersByte/bs-material-ui pull request #29
Opened 2017-11-16 23:46 UTC by bernalrs

Ready for review.

2017-12-29 15:59 UTC, pahund approved these changes

2018-01-16 12:14 UTC, InsidersByte requested changes

2018-01-16 12:14 UTC, InsidersByte commented on src/MaterialUI.re
> +module BottomNavigationButton = {
renamed to BottomNavigationAction

2018-01-16 12:14 UTC, InsidersByte commented on src/MaterialUI.re
> +        ~icon: option([ | `String(string) | `ReactElement(ReasonReact.reactElement)])=?,
need to double check this works correctly

2018-01-16 12:14 UTC, InsidersByte commented on src/MaterialUI.re
> +        ~value: option([ | `String(string) | `Int(int) | `Float(float)])=?,
this should be **'a**

2018-01-16 12:14 UTC, InsidersByte commented on src/MaterialUI.re
> +        ~value: option([ | `Int(int) | `String(string) | `Float(float)])=?,
this should be **'a** and above **style**

2018-01-16 12:14 UTC, InsidersByte commented on src/MaterialUI.re
> +            "showLabels": from_opt(showLabels),
this should use unwrap_bool

2018-04-16 13:36 UTC, InsidersByte commented
this will be added in #55

2018-04-16 13:36 UTC, closed without merging