feat: add Slide, add classes prop to LinearProgress
InsidersByte/bs-material-ui pull request #34
Opened 2017-12-07 02:46 UTC by javamonn

- Adds the [`Slide`](https://material-ui-next.com/api/slide/) component, but does not props that the underlying `Transition` would use.
- Adds the `classes` prop to the existing `LinearProgress` component.

2017-12-12 10:55 UTC, bernalrs commented on src/MaterialUI.re
> +        ~timeout: option({. "enter": float, "exit": float})=?,
The docs specify you should be able to provide a single float (or number in js) value as well.

2017-12-12 10:56 UTC, bernalrs commented on src/MaterialUI.re
> +      ) =>
There are also some events missign which have been omitted from the docs.

  onEnter?: TransitionCallback, 
  onEntering?: TransitionCallback,
  onEntered?: TransitionCallback,
  onExit?: TransitionCallback,
  onExiting?: TransitionCallback,
  onExited?: TransitionCallback,

2017-12-12 10:56 UTC, bernalrs requested changes
Few comment inline.

2017-12-12 11:04 UTC, bernalrs commented on src/MaterialUI.re
> +      ) =>
Should also include the properties of the Transition class:

  appear?: boolean;
  unmountOnExit?: boolean;

2018-04-16 13:35 UTC, InsidersByte commented
this will be added in #55

2018-04-16 13:35 UTC, closed without merging